typedef enum
{
    SIMONSAYS_STATE_NEW_GAME,
    SIMONSAYS_STATE_ADD_COLOR,
    SIMONSAYS_STATE_SHOW_SEQUENCE,
    SIMONSAYS_STATE_WAIT_PLAYER,
    SIMONSAYS_STATE_SUCCESS,
    SIMONSAYS_STATE_GAME_OVER
} SimonState;