#ifndef SIMON_SAYS_STATE_H
#define SIMON_SAYS_STATE_H

typedef enum
{
    SIMONSAYS_STATE_NEW_GAME = 0,
    SIMONSAYS_STATE_ADD_COLOUR,
    SIMONSAYS_STATE_SHOW_SEQUENCE,
    SIMONSAYS_STATE_WAIT_PLAYER,
    SIMONSAYS_STATE_NEXT_ROUND,
    SIMONSAYS_STATE_GAME_OVER

} SimonState;

#endif